source 'https://rubygems.org'
ruby '2.2.3'

## Gem versioning syntax examples
#
# ~> 2.0.0 == (>= 2.0.0 && < 2.1)
# ~> 2.1   == (>= 2.1   && < 3.0)

group :test, :development do
  	gem 'byebug'   # lets you set debugging breakpoints by typing "byebug" in your code;  similar to Chrome's "debugger;" in javascript
  	gem 'konacha'
  	gem 'teaspoon'
  	gem 'poltergeist'
end

group :doc do
    gem 'sdoc', require: false    # bundle exec rake doc:rails generates the API under doc/api.
end


# per https://devcenter.heroku.com/articles/getting-started-with-rails4

gem 'devise'
gem 'therubyracer'

gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2'

gem 'rails_12factor', group: :production   # https://devcenter.heroku.com/articles/getting-started-with-rails4#heroku-gems

#gem 'jquery-cdn'               # TODO figure this out # jQuery 2.x;  the jquery-rails gem was still only offering jQuery 1.10, as of 4/20/14.
gem 'annotate'                  # used to generate comments in each of your model files, documenting that model's underlying SQL schema
gem 'bcrypt-ruby', '~> 3.0.0'   # use ActiveModel has_secure_password
gem 'cancan', '>= 1.6.10'
gem 'closure-compiler'          # Google's Closure Compiler for javascript minimization and performance enhancements
gem 'hstore_accessor'           # for accessing Postgres hstore columns as objects
gem 'jbuilder', '~> 1.0.1'      # build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jquery-rails'              # use jquery as the JavaScript library
gem 'jquery-ui-rails', '4.2.1'  # TODO(2015.09.25) eventually upgrade to the 5.x version;  check "gem list jquery" to see which exact multiple versions you have installed already...
gem 'pg'                        # use postgresql as the database for Active Record
gem 'rails', '4.2.4'            # bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'RedCloth'                  # used to generate the Ruby-on-Rails tutorial documentation in ./doc/

gem 'sass-rails', '~> 5.0'      # use SCSS for stylesheets
gem 'foundation-rails'
#gem 'compass-rails', '~> 2.0'   # use the Compass framework, https://github.com/compass/compass-rails -- it builds atop SCSS to give you helps like "rem-calc(10)"

gem 'turbolinks'                # Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'rolify', '>= 4.1.1'
gem 'twitter-bootstrap-rails', :git => 'git://github.com/seyhunak/twitter-bootstrap-rails.git'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
